# -*- coding: utf-8 -*-
{
    'name': "Report List",
    'summary': """Quản lý báo cáo số dư và báo cáo giao dịch.""",
    'description': """Module này cung cấp các chức năng để quản lý báo cáo số dư và báo cáo giao dịch.""",
    'author': "Your Company Name",
    'website': "https://www.yourcompany.com",
    'category': '',
    'version': '18.0.0.0.23',
    'depends': ['base', 'crm', 'web', 'transaction_list', 'transaction_management', 'overview_fund_management', 'investor_profile_management'],

    'data': [
        'security/ir.model.access.csv',
        'views/report_balance/report_balance_page.xml',
        'views/report_balance/report_balance_pdf_template.xml',
        'views/report_transaction/report_transaction_page.xml',
        'views/report_transaction/report_transaction_pdf_template.xml',
        'views/report_order_history/report_order_history_page.xml',
        'views/report_order_history/report_order_history_pdf_template.xml',
        'views/report_contract_statistics/report_contract_statistics_page.xml',
        'views/report_contract_statistics/report_contract_statistics_pdf_template.xml',
        'views/report_early_sale/report_early_sale_page.xml',
        'views/report_early_sale/report_early_sale_pdf_template.xml',
        'views/report_contract_summary/report_contract_summary_page.xml',
        'views/report_contract_summary/report_contract_summary_pdf_template.xml',
        'views/report_purchase_contract/report_purchase_contract_page.xml',
        'views/report_purchase_contract/report_purchase_contract_pdf_template.xml',
        'views/report_sell_contract/report_sell_contract_page.xml',
        'views/report_sell_contract/report_sell_contract_pdf_template.xml',
        'views/aoc_report/aoc_report_page.xml',
        'views/aoc_report/aoc_report_pdf_template.xml',
        'views/investor_report/investor_report_page.xml',
        'views/investor_report/investor_report_pdf_template.xml',
        'views/user_list_report/user_list_report_page.xml',
        'views/user_list_report/user_list_report_pdf_template.xml',
        'views/list_tenors_interest_rates/list_tenors_interest_rates_page.xml',
        'views/list_tenors_interest_rates/list_tenors_interest_rates_pdf_template.xml',
    ],

    'assets': {
        'web.assets_frontend': [
            'report_list/static/src/css/report-list.css',
            'report_list/static/src/js/report_balance/report_balance_widget.js',
            'report_list/static/src/js/report_transaction/report_transaction_widget.js',
            'report_list/static/src/js/report_order_history/report_order_history_widget.js',
            'report_list/static/src/js/report_contract_statistics/report_contract_statistics_widget.js',
            'report_list/static/src/js/report_early_sale/report_early_sale_widget.js',
            'report_list/static/src/js/report_contract_summary/report_contract_summary_widget.js',
            'report_list/static/src/js/report_purchase_contract/report_purchase_contract_widget.js',
            'report_list/static/src/js/report_sell_contract/report_sell_contract_widget.js',
            'report_list/static/src/js/aoc_report/aoc_report_widget.js',
            'report_list/static/src/js/investor_report/investor_report_widget.js',
            'report_list/static/src/js/user_list_report/user_list_report_widget.js',
            'report_list/static/src/js/list_tenors_interest_rates/list_tenors_interest_rates_widget.js',
            'report_list/static/src/js/report_balance/entrypoint.js',
            'report_list/static/src/js/report_transaction/entrypoint.js',
            'report_list/static/src/js/report_order_history/entrypoint.js',
            'report_list/static/src/js/report_contract_statistics/entrypoint.js',
            'report_list/static/src/js/report_early_sale/entrypoint.js',
            'report_list/static/src/js/report_contract_summary/entrypoint.js',
            'report_list/static/src/js/report_purchase_contract/entrypoint.js',
            'report_list/static/src/js/report_sell_contract/entrypoint.js',
            'report_list/static/src/js/aoc_report/entrypoint.js',
            'report_list/static/src/js/investor_report/entrypoint.js',
            'report_list/static/src/js/user_list_report/entrypoint.js',
            'report_list/static/src/js/list_tenors_interest_rates/entrypoint.js',
        ],
    },

    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}